version: '3'
services: 
  mysql:
    image: mysql:8.0.25
    restart: always
    container_name: lilishop-mysql
    ports:
      - 3301:3306
    volumes:
      - ./data/mysqldata:/var/lib/mysql
      - ./config/my.cnf:/etc/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - ./init/mysql:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=lilishop"
      - "MYSQL_DATABASE=lilishop"
      - "TZ=Asia/Shanghai"
    networks:
      - lilishop

  mongo:
    image: mongo:5.0.2
    restart: always
    container_name: lilishop-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: lilishop
    ports:
      - 27011:27017
    volumes: 
      - ./data/mongodata:/data/db
    networks:
      - lilishop

  redis:
    image: redis:6.2.5
    restart: always
    container_name: lilishop-redis
    ports:
      - 6380:6379
    volumes: 
      - ./data/redsidata:/data
    command: redis-server --port 6379 --requirepass lilishop --appendonly yes
    networks:
      - lilishop

  elasticsearch:
    image: elasticsearch:7.3.0
    restart: always
    container_name: elasticsearch
    volumes:
      - ./data/es7/logs:/usr/share/es7/logs:rw
      - ./data/es7/data:/usr/share/es7/data:rw
      - ./config/ik:/usr/share/elasticsearch/plugins/ik
      # - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment:
      cluster.name: elasticsearch
      discovery.type: single-node
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks: 
      - lilishop
    ulimits:
      nofile:
          soft: 65535
          hard: 65535

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    restart: always
    container_name: kibana
    ports:
      - 5601:5601
    # volumes:
    #   - "./config/kibana.yml:/usr/share/kibana/config/kibana.yml"
    networks: 
      - lilishop
    depends_on: ['elasticsearch']  


  logstash:
    image: logstash:7.3.0
    restart: always
    container_name: logstash
    volumes:
      - ./config/logstash-springboot.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    networks: 
      - lilishop
    depends_on: ['elasticsearch']
    ports: 
      - 4560:4560
    
 # rocket mq name server
  rmqnamesrv:
    image: foxiswho/rocketmq:server-4.7.0
    restart: always
    container_name: rocket-server
    environment:
      JAVA_OPT_EXT: "-server -Xms64m -Xmx64m -Xmn64m"
    volumes:
      - ./data/rocket/server/logs:/opt/logs
      - ./data/rocket/server/store:/opt/rmqstore
    networks:
      - lilishop
    ports:
      - 9876:9876
  # rocket mq broker
  rmqbroker:
    image: foxiswho/rocketmq:broker-4.7.0
    restart: always
    container_name: rocket-broker
    volumes:
      - ./data/rocket/broker/logs:/opt/logs
      - ./data/rocket/broker/store:/opt/rmqstore
      - ./config/broker.conf:/etc/rocketmq/broker.conf
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
      - JAVA_OPTS:=-Duser.home=/opt
      - JAVA_OPT_EXT=-server -Xms64m -Xmx64m -Xmn64m
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rmqnamesrv
    networks:
      - lilishop
    ports:
      - 10909:10909
      - 10911:10911
  # rocket console 这个可以不需要
  rmqconsole:
    image: styletang/rocketmq-console-ng:latest
    restart: always
    container_name: rocket-console
    environment:
      - JAVA_OPTS=-Drocketmq.config.namesrvAddr=rmqnamesrv:9876 -Dserver.port=8180 -Drocketmq.config.isVIPChannel=false
      - JAVA_OPT_EXT=-Xms128m -Xmx128m -Xmn128m
    depends_on:
      - rmqnamesrv
    networks:
      - lilishop
    ports:
      - 8180:8180
  # xxl-job 分布式调度中心
  xxl-job:
    image: xuxueli/xxl-job-admin:2.3.0
    restart: always
    container_name: xxl-job
    networks:
      - lilishop
    ports:
      - 9003:9001
    environment:
      - PARAMS=--spring.datasource.url=jdbc:mysql://mysql:3306/lilishop?Unicode=true&characterEncoding=UTF-8  --spring.datasource.username=root --spring.datasource.password=lilishop --server.port=9001
    depends_on:
      - mysql
    volumes:
      - ./data/xxl-job:/data/applogs

  buyer:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/luomor/buyer-api:4.2.5.1
    container_name: buyer
    ports:
      - 8888:8888
    networks:
      - lilishop
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC

  common:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/luomor/common-api:4.2.5.1
    container_name: common
    ports:
      - 8890:8890
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    networks:
      - lilishop

  # 8886
  seller:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/luomor/seller-api:4.2.5.1
    container_name: seller
    ports:
      - 8889:8889
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    networks:
      - lilishop

  manager:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/luomor/manager-api:4.2.5.1
    container_name: manager
    ports:
      - 8887:8887
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    networks:
      - lilishop

  buyer-ui:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/luomor/buyer-ui:4.2.4.1
    container_name: buyer-ui
    ports:
      - 8021:10000
    networks:
      - lilishop

  seller-ui:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/luomor/seller-ui:4.2.4.1
    container_name: seller-ui
    ports:
      - 8022:10002
    networks:
      - lilishop

  manager-ui:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/luomor/manager-ui:4.2.4.1
    container_name: manager-ui
    ports:
      - 8023:10003
    networks:
      - lilishop
networks: 
  lilishop:
    driver: bridge
